spring:
  application:
    name: gw-app

server:
  port: 10201

zuul:

  sensitive-headers: 
  
  routes:
    account-app:
      path: /account/**
      serviceId: account-app
    article-app:
      path: /article/**
      serviceId: article-app